### ISSUE TITLE
Kit support

### ISSUE THREAD

**Issue by Clean-Cole** [mParticle/mparticle-flutter-sdk#30]
In order to support a kit integration in flutter we are required to create another local plugin with its own podspec file to create dependencies for things like Braze and Radar.

## Current Workaround

```ruby
# File:
# counter_app/special_plugin/ios/special_plugin.podspec

Pod::Spec.new do |s|
  s.name             = 'special_plugin'
  s.dependency 'mParticle-Appboy'
  s.dependency 'mParticle-Radar'
  s.dependency 'mParticle-Google-Analytics-Firebase'
  s.static_framework = true
end
```

```yaml
name: counter_app
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  mparticle_flutter_sdk: ^1.0.0-beta.1
  special_plugin:
    path: special_plugin
```

## Proposed fix:

Turn this repo into a mono-repo of multiple flutter plugin projects that each point to a single kit integration.  I don't even think any platform channel creation would be necessary, just need to simply load the dependencies into maven and cocoapods.

```yaml
name: counter_app
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  mparticle_flutter_sdk: ^1.0.0-beta.1
  mparticle_kit_appboy: ^1.0.0-beta.1
  mparticle_kit_radar: ^1.0.0-beta.1
  mparticle_kit_google_analytics: ^1.0.0-beta.1
```

Maybe there is a better way for the Flutter framework to handle this use case, but I have not been able to find clear documentation.

Thoughts?
